### ISSUE TITLE
Given Clare and Megan access to s3

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/OIF-Pipeline-Orchestration#11]
We want to give @clarebetts-code access to our s3 bucket so she (and anyone else working on OIF projects) can use the transformed dataframes created by the processing pipeline.

**Comment by EFT-Defra** [comment]
I've requested access on the SCE slack.

**Comment by EFT-Defra** [comment]
Clare should have access via her SCE VM, I've asked her to test it.

**Comment by EFT-Defra** [comment]
Still waiting for feedback from Clare.

**Comment by clarebetts-code** [comment]
successfully connected!
